<?php

namespace App\Http\Requests\Contact;

use App\Rules\PhoneNumber;
use Illuminate\Foundation\Http\FormRequest;

class NewContactRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'nome' => 'required',
            'email' => 'required|email',
            'mensagem' => 'required',
            'arquivo' => 'required|mimes:pdf,doc,docx,odt,txt|max:500',
            'telefone' => new PhoneNumber
        ];
    }

    public function messages()
    {
        parent::messages(); // TODO: Change the autogenerated stub
        return [
            'nome.required' => 'O campo :attribute é obrigatório',
            'email.required' =>  'O campo :attribute é obrigatório',
            'email.email' =>  'O campo :attribute não é um email válido',
            'mensagem.required' => 'O campo :attribute é obrigatório',
            'arquivo.required' =>  'O campo :attribute é obrigatório',
            'arquivo.mimes' =>  'O campo arquivo só aceita os seguintes formatos: :values',
            'arquivo.max' => 'O tamanho de arquivo não pode ser maior que 500 (kb)'
        ];
    }
}
